//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.HsuanMoveitCommand
{
    [Serializable]
    public class HsuanMoveServiceRequest : Message
    {
        public const string k_RosMessageName = "hsuan_moveit_command/HsuanMoveService";
        public override string RosMessageName => k_RosMessageName;

        public HsuanMoveitJointsMsg hsuan_moveit_joints;

        public HsuanMoveServiceRequest()
        {
            this.hsuan_moveit_joints = new HsuanMoveitJointsMsg();
        }

        public HsuanMoveServiceRequest(HsuanMoveitJointsMsg hsuan_moveit_joints)
        {
            this.hsuan_moveit_joints = hsuan_moveit_joints;
        }

        public static HsuanMoveServiceRequest Deserialize(MessageDeserializer deserializer) => new HsuanMoveServiceRequest(deserializer);

        private HsuanMoveServiceRequest(MessageDeserializer deserializer)
        {
            this.hsuan_moveit_joints = HsuanMoveitJointsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hsuan_moveit_joints);
        }

        public override string ToString()
        {
            return "HsuanMoveServiceRequest: " +
            "\nhsuan_moveit_joints: " + hsuan_moveit_joints.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
