//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.HsuanMoveitCommand
{
    [Serializable]
    public class HsuanMoveitJointsMsg : Message
    {
        public const string k_RosMessageName = "hsuan_moveit_command/HsuanMoveitJoints";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg start_joint_state;
        public Sensor.JointStateMsg end_joint_state;
        public Geometry.PoseMsg start_pose;
        public Geometry.PoseMsg end_pose;
        public float speed_factor;

        public HsuanMoveitJointsMsg()
        {
            this.start_joint_state = new Sensor.JointStateMsg();
            this.end_joint_state = new Sensor.JointStateMsg();
            this.start_pose = new Geometry.PoseMsg();
            this.end_pose = new Geometry.PoseMsg();
            this.speed_factor = 0.0f;
        }

        public HsuanMoveitJointsMsg(Sensor.JointStateMsg start_joint_state, Sensor.JointStateMsg end_joint_state, Geometry.PoseMsg start_pose, Geometry.PoseMsg end_pose, float speed_factor)
        {
            this.start_joint_state = start_joint_state;
            this.end_joint_state = end_joint_state;
            this.start_pose = start_pose;
            this.end_pose = end_pose;
            this.speed_factor = speed_factor;
        }

        public static HsuanMoveitJointsMsg Deserialize(MessageDeserializer deserializer) => new HsuanMoveitJointsMsg(deserializer);

        private HsuanMoveitJointsMsg(MessageDeserializer deserializer)
        {
            this.start_joint_state = Sensor.JointStateMsg.Deserialize(deserializer);
            this.end_joint_state = Sensor.JointStateMsg.Deserialize(deserializer);
            this.start_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.end_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.speed_factor);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_joint_state);
            serializer.Write(this.end_joint_state);
            serializer.Write(this.start_pose);
            serializer.Write(this.end_pose);
            serializer.Write(this.speed_factor);
        }

        public override string ToString()
        {
            return "HsuanMoveitJointsMsg: " +
            "\nstart_joint_state: " + start_joint_state.ToString() +
            "\nend_joint_state: " + end_joint_state.ToString() +
            "\nstart_pose: " + start_pose.ToString() +
            "\nend_pose: " + end_pose.ToString() +
            "\nspeed_factor: " + speed_factor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
